name: phoneme
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-265.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  image_picker: ^1.1.2
  pdf: ^3.11.3
  excel: ^4.0.6
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  fl_chart: ^0.71.0
  carousel_slider: ^5.0.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Declarar los assets aquí, correctamente indentados.
  assets:
    - assets/logo.png
    - assets/images/phonetics.png
    - assets/images/phonology.png
    - assets/images/vocalization.png
